openapi: 3.0.2
info:
  version: '1.1'
  title: SFG Pub API
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
  contact:
    name: John Thompson
    url: 'https://springframework.guru'
servers:
  - url: 'http://localhost:8080'
    description: Local Host
tags:
  - name: Beer
    description: Beer Operations
  - name: Customer
    description: Customer Operations
  - name: Order
    description: Order Operations
paths:
  /api/v1/beer:
    get:
      description: List Beers
      tags:
        - Beer
      parameters:
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/BeerName'
        - $ref: '#/components/parameters/BeerStyle'
      responses:
        '200':
          description: List Beers Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeerPagedList'
  '/api/v1/beer/{beerId}':
    parameters:
      - $ref: '#/components/parameters/BeerId'
    get:
      description: Get Beer by Id
      tags:
        - Beer
      responses:
        '200':
          description: List Beers Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Beer'
        '404':
          description: Not Found
  /api/v1/customers:
    post:
      description: Register as new customer
      tags:
        - Customer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer Created
          headers:
            Location:
              description: Reference to created customer
              schema:
                type: string
                format: uri
        '400':
          description: Bad Request
  '/api/v1/customers/{customerId}':
    parameters:
      - $ref: '#/components/parameters/CustomerId'
    get:
      description: Get customer by Id
      tags:
        - Customer
      responses:
        '200':
          description: HTTP Okay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Not Found
  '/api/v1/customers/{customerId}/orders':
    parameters:
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/PageSize'
    get:
      description: List Orders
      tags:
        - Order
      responses:
        '200':
          description: List Order Reponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeerOrderPagedList'
    post:
      description: Place Order
      tags:
        - Order
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeerOrder'
      responses:
        '201':
          description: Order Created
          headers:
            Location:
              description: Reference to created Order
              schema:
                type: string
                format: uri
        '404':
          description: Not Found
      callbacks:
        orderStatusChange:
          '{$request.body#/orderStatusCallback}':
            description: Webhook post to reecive notifcations of order status changes.
            post:
              requestBody:
                $ref: '#/components/requestBodies/OrderStatusCallback'
              responses:
                '200':
                  description: Okay
  '/api/v1/customers/{customerId}/orders/{orderId}':
    parameters:
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/OrderId'
    get:
      description: Get Order By Id
      tags:
        - Order
      responses:
        '200':
          description: HTTP Okay
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeerOrder'
        '404':
          description: Customer Id or Order Id Not Found
  '/api/v1/customers/{customerId}/orders/{orderId}/pickup':
    parameters:
      - $ref: '#/components/parameters/CustomerId'
      - $ref: '#/components/parameters/OrderId'
    put:
      description: Pickup Order
      tags:
        - Order
      responses:
        '204':
          description: No Content
        '404':
          description: Customer Id or Order Id Not Found
components:
  parameters:
    BeerId:
      name: beerId
      in: path
      description: Beer Id
      required: true
      schema:
        type: string
        format: uuid
    BeerName:
      name: beerName
      in: query
      description: Beer Name
      required: false
      schema:
        type: string
    BeerStyle:
      name: beerStyle
      in: query
      description: Beer Style
      required: false
      schema:
        type: string
    CustomerId:
      name: customerId
      in: path
      description: Customer Id
      required: true
      schema:
        type: string
        format: uuid
    Page:
      name: pageNumber
      in: query
      description: Page number.
      required: false
      schema:
        type: integer
        format: int32
        default: 1
    PageSize:
      name: pageSize
      in: query
      description: Page size.
      required: false
      schema:
        type: integer
        format: int32
        default: 25
    OrderId:
      name: orderId
      in: path
      description: Order Id
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    BaseItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          nullable: true
        version:
          type: integer
          readOnly: true
          nullable: true
        createdDate:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        lastModifiedDate:
          type: string
          format: date-time
          readOnly: true
          nullable: true
    Beer:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      required:
        - beerName
        - beerStyle
        - quantityOnHand
        - price
        - upc
      properties:
        beerName:
          type: string
        beerStyle:
          $ref: '#/components/schemas/BeerStyleEnum'
        upc:
          type: integer
        quantityOnHand:
          type: integer
        price:
          type: string
          format: decimal
    BeerPagedList:
      type: object
      allOf:
        - $ref: '#/components/schemas/PagedResponse'
      properties:
        content:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Beer'
    BeerOrder:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        customerId:
          type: string
          format: uuid
        customerRef:
          type: string
          nullable: true
        beerOrderLines:
          type: array
          items:
            $ref: '#/components/schemas/BeerOrderLine'
        orderStatus:
          $ref: '#/components/schemas/OrderStatusEnum'
        orderStatusCallbackUrl:
          type: string
          format: uri
    BeerOrderPagedList:
      type: object
      allOf:
        - $ref: '#/components/schemas/PagedResponse'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/BeerOrder'
    BeerOrderLine:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        beerId:
          type: string
          format: uuid
        quantity:
          type: integer
          minimum: 1
          maximum: 999
    BeerStyleEnum:
      type: string
      enum:
        - LAGER
        - PILSNER
        - STOUT
        - GOSE
        - PORTER
        - ALE
        - WHEAT
        - IPA
        - PALE_ALE
        - SAISON
    Customer:
      type: object
      required:
        - name
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        name:
          type: string
          maxLength: 255
          minLength: 1
    PagedResponse:
      type: object
      properties:
        pageable:
          type: object
          properties:
            sort:
              type: object
              properties:
                sorted:
                  type: boolean
                unsorted:
                  type: boolean
            offset:
              type: integer
              format: int32
            pageNumber:
              type: integer
              format: int32
            pageSize:
              type: integer
              format: int32
            paged:
              type: boolean
            unpaged:
              type: boolean
        totalPages:
          type: integer
          format: int32
        last:
          type: boolean
        totalElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        sort:
          type: object
          properties:
            sorted:
              type: boolean
            unsorted:
              type: boolean
        first:
          type: boolean
    OrderStatusEnum:
      type: string
      nullable: true
      enum:
        - NEW
        - READY
        - PICKED_UP
    OrderStatusUpdate:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        orderId:
          type: string
          format: uuid
        customerRef:
          type: string
        orderStatus:
          $ref: '#/components/schemas/OrderStatusEnum'
  requestBodies:
    OrderStatusCallback:
      description: Order Status Update
      content:
        application/json:
          schema:
            type: object
            properties:
              orderId:
                type: string
                format: uuid
              orderStatus:
                $ref: '#/components/schemas/OrderStatusUpdate'
